name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build and Export Next.js app
        run: |
          cd apps/next
          npx next build
          npx next export
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next-app-out
          path: apps/next/out
          if-no-files-found: error
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: next-app-out
          path: apps/next/out
      - name: Deploy
        run: |
          rm -rf public
          mv apps/next/out public
      - name: Upload Public to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          if-no-files-found: error
          retention-days: 7
